name: Build & Push Docker Hub Images
on:
  push:
    branches:
      - main

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile.base
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/codedswitch-backend-base:latest

  build-and-push-backend:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push app image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile.backend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/codedswitch-backend:latest
